apiVersion: v1
kind: Service
metadata:
  name: binary-calculator-service
spec:
  type: LoadBalancer
  selector:
    app: binary-calculator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080